use strum::{Display, EnumString, FromRepr};

use super::prelude::SymbolType;

#[derive(
    Debug,
    PartialEq,
    Eq,
    PartialOrd,
    Ord,
    Hash,
    Clone,
    Copy,
    EnumString,
    Display,
    FromRepr,
    serde::Serialize,
    serde::Deserialize,
)]
#[repr(u8)]

pub enum Symbol {
    AA = 1,
    AA0 = 2,
    AA1 = 3,
    AA2 = 4,
    AE = 5,
    AE0 = 6,
    AE1 = 7,
    AE2 = 8,
    AH = 9,
    AH0 = 10,
    AH1 = 11,
    AH2 = 12,
    AO = 13,
    AO0 = 14,
    AO1 = 15,
    AO2 = 16,
    AW = 17,
    AW0 = 18,
    AW1 = 19,
    AW2 = 20,
    AY = 21,
    AY0 = 22,
    AY1 = 23,
    AY2 = 24,
    B = 25,
    CH = 26,
    D = 27,
    DH = 28,
    EH = 29,
    EH0 = 30,
    EH1 = 31,
    EH2 = 32,
    ER = 33,
    ER0 = 34,
    ER1 = 35,
    ER2 = 36,
    EY = 37,
    EY0 = 38,
    EY1 = 39,
    EY2 = 40,
    F = 41,
    G = 42,
    HH = 43,
    IH = 44,
    IH0 = 45,
    IH1 = 46,
    IH2 = 47,
    IY = 48,
    IY0 = 49,
    IY1 = 50,
    IY2 = 51,
    JH = 52,
    K = 53,
    L = 54,
    M = 55,
    N = 56,
    NG = 57,
    OW = 58,
    OW0 = 59,
    OW1 = 60,
    OW2 = 61,
    OY = 62,
    OY0 = 63,
    OY1 = 64,
    OY2 = 65,
    P = 66,
    R = 67,
    S = 68,
    SH = 69,
    T = 70,
    TH = 71,
    UH = 72,
    UH0 = 73,
    UH1 = 74,
    UH2 = 75,
    UW = 76,
    UW0 = 77,
    UW1 = 78,
    UW2 = 79,
    V = 80,
    W = 81,
    Y = 82,
    Z = 83,
    ZH = 84,
}

impl Symbol {
    pub fn is_vowel(self) -> bool {
        self.symbol_type().is_vowel()
    }

    pub fn is_stressed_vowel(self) -> bool {
        self.symbol_type() == SymbolType::StressedVowel
    }

    pub fn normalize_vowel(self) -> Self {
        match self {
            Symbol::AA0 => Symbol::AA,
            Symbol::AA1 => Symbol::AA,
            Symbol::AA2 => Symbol::AA,

            Symbol::AE0 => Symbol::AE,
            Symbol::AE1 => Symbol::AE,
            Symbol::AE2 => Symbol::AE,

            Symbol::AH0 => Symbol::AH,
            Symbol::AH1 => Symbol::AH,
            Symbol::AH2 => Symbol::AH,

            Symbol::AO0 => Symbol::AO,
            Symbol::AO1 => Symbol::AO,
            Symbol::AO2 => Symbol::AO,

            Symbol::AW0 => Symbol::AW,
            Symbol::AW1 => Symbol::AW,
            Symbol::AW2 => Symbol::AW,

            Symbol::AY0 => Symbol::AY,
            Symbol::AY1 => Symbol::AY,
            Symbol::AY2 => Symbol::AY,

            Symbol::EH0 => Symbol::EH,
            Symbol::EH1 => Symbol::EH,
            Symbol::EH2 => Symbol::EH,

            Symbol::ER0 => Symbol::ER,
            Symbol::ER1 => Symbol::ER,
            Symbol::ER2 => Symbol::ER,

            Symbol::EY0 => Symbol::EY,
            Symbol::EY1 => Symbol::EY,
            Symbol::EY2 => Symbol::EY,

            Symbol::IH0 => Symbol::IH,
            Symbol::IH1 => Symbol::IH,
            Symbol::IH2 => Symbol::IH,

            Symbol::IY0 => Symbol::IY,
            Symbol::IY1 => Symbol::IY,
            Symbol::IY2 => Symbol::IY,

            Symbol::OW0 => Symbol::OW,
            Symbol::OW1 => Symbol::OW,
            Symbol::OW2 => Symbol::OW,

            Symbol::OY0 => Symbol::OY,
            Symbol::OY1 => Symbol::OY,
            Symbol::OY2 => Symbol::OY,

            Symbol::UH0 => Symbol::UH,
            Symbol::UH1 => Symbol::UH,
            Symbol::UH2 => Symbol::UH,

            Symbol::UW0 => Symbol::UW,
            Symbol::UW1 => Symbol::UW,
            Symbol::UW2 => Symbol::UW,
            _ => self,
        }
    }

    pub fn symbol_type(self) -> SymbolType {
        match self {
            Symbol::AA => SymbolType::UnstressedVowel,
            Symbol::AE => SymbolType::UnstressedVowel,
            Symbol::AH => SymbolType::UnstressedVowel,
            Symbol::AO => SymbolType::UnstressedVowel,
            Symbol::AW => SymbolType::UnstressedVowel,
            Symbol::AY => SymbolType::UnstressedVowel,
            Symbol::EH => SymbolType::UnstressedVowel,
            Symbol::ER => SymbolType::UnstressedVowel,
            Symbol::EY => SymbolType::UnstressedVowel,
            Symbol::IH => SymbolType::UnstressedVowel,
            Symbol::IY => SymbolType::UnstressedVowel,
            Symbol::OW => SymbolType::UnstressedVowel,
            Symbol::OY => SymbolType::UnstressedVowel,
            Symbol::UH => SymbolType::UnstressedVowel,
            Symbol::UW => SymbolType::UnstressedVowel,

            Symbol::AA0 => SymbolType::UnstressedVowel,
            Symbol::AE0 => SymbolType::UnstressedVowel,
            Symbol::AH0 => SymbolType::UnstressedVowel,
            Symbol::AO0 => SymbolType::UnstressedVowel,
            Symbol::AW0 => SymbolType::UnstressedVowel,
            Symbol::AY0 => SymbolType::UnstressedVowel,
            Symbol::EH0 => SymbolType::UnstressedVowel,
            Symbol::ER0 => SymbolType::UnstressedVowel,
            Symbol::EY0 => SymbolType::UnstressedVowel,
            Symbol::IH0 => SymbolType::UnstressedVowel,
            Symbol::IY0 => SymbolType::UnstressedVowel,
            Symbol::OW0 => SymbolType::UnstressedVowel,
            Symbol::OY0 => SymbolType::UnstressedVowel,
            Symbol::UH0 => SymbolType::UnstressedVowel,
            Symbol::UW0 => SymbolType::UnstressedVowel,

            Symbol::AA1 => SymbolType::StressedVowel,
            Symbol::AE1 => SymbolType::StressedVowel,
            Symbol::AH1 => SymbolType::StressedVowel,
            Symbol::AO1 => SymbolType::StressedVowel,
            Symbol::AW1 => SymbolType::StressedVowel,
            Symbol::AY1 => SymbolType::StressedVowel,
            Symbol::EH1 => SymbolType::StressedVowel,
            Symbol::ER1 => SymbolType::StressedVowel,
            Symbol::EY1 => SymbolType::StressedVowel,
            Symbol::IH1 => SymbolType::StressedVowel,
            Symbol::IY1 => SymbolType::StressedVowel,
            Symbol::OW1 => SymbolType::StressedVowel,
            Symbol::OY1 => SymbolType::StressedVowel,
            Symbol::UH1 => SymbolType::StressedVowel,
            Symbol::UW1 => SymbolType::StressedVowel,

            Symbol::AA2 => SymbolType::StressedVowel,
            Symbol::AE2 => SymbolType::StressedVowel,
            Symbol::AH2 => SymbolType::StressedVowel,
            Symbol::AO2 => SymbolType::StressedVowel,
            Symbol::AW2 => SymbolType::StressedVowel,
            Symbol::AY2 => SymbolType::StressedVowel,
            Symbol::EH2 => SymbolType::StressedVowel,
            Symbol::ER2 => SymbolType::StressedVowel,
            Symbol::EY2 => SymbolType::StressedVowel,
            Symbol::IH2 => SymbolType::StressedVowel,
            Symbol::IY2 => SymbolType::StressedVowel,
            Symbol::OW2 => SymbolType::StressedVowel,
            Symbol::OY2 => SymbolType::StressedVowel,
            Symbol::UH2 => SymbolType::StressedVowel,
            Symbol::UW2 => SymbolType::StressedVowel,

            Symbol::B => SymbolType::Stop,
            Symbol::CH => SymbolType::Affricate,
            Symbol::D => SymbolType::Stop,
            Symbol::DH => SymbolType::Fricative,
            Symbol::F => SymbolType::Fricative,
            Symbol::G => SymbolType::Stop,
            Symbol::HH => SymbolType::Aspirate,
            Symbol::JH => SymbolType::Affricate,
            Symbol::K => SymbolType::Stop,
            Symbol::L => SymbolType::Liquid,
            Symbol::M => SymbolType::Nasal,
            Symbol::N => SymbolType::Nasal,
            Symbol::NG => SymbolType::Nasal,
            Symbol::P => SymbolType::Stop,
            Symbol::R => SymbolType::Liquid,
            Symbol::S => SymbolType::Fricative,
            Symbol::SH => SymbolType::Fricative,
            Symbol::T => SymbolType::Stop,
            Symbol::TH => SymbolType::Fricative,
            Symbol::V => SymbolType::Fricative,
            Symbol::W => SymbolType::Semivowel,
            Symbol::Y => SymbolType::Semivowel,
            Symbol::Z => SymbolType::Fricative,
            Symbol::ZH => SymbolType::Fricative,
        }
    }
}
